services:
  client:
    build: ./client
    ports:
        - 8080:8080

  server:
    build: ./server
    ports:
        - 5000:5000
    volumes:
      - type: bind
        source: ./server
        target: /app